### ISSUE TITLE
Transformations do not account for order of operations

### ISSUE THREAD

**Issue by jdufresne** [pytest-dev/unittest2pytest#29]
Example input:

```py
class MyTest(unittest.TestCase):
    def test_thing(self):
        self.assertEqual(my_func(), expected_string() or None)
```

Output:

```diff
@@ -1,3 +1,3 @@
 class MyTest(unittest.TestCase):
     def test_thing(self):
-        self.assertEqual(my_func(), expected_value() or None)
+        assert my_func() == expected_value() or None
```
Due to [Python's order of operations](https://docs.python.org/3/reference/expressions.html#operator-precedence), this changes the semantics of the assert. The `or` operation now happens _after_ the `==` operation. 

Expected output:

```diff
@@ -1,3 +1,3 @@
 class MyTest(unittest.TestCase):
     def test_thing(self):
-        self.assertEqual(my_func(), expected_value() or None)
+        assert my_func() == (expected_value() or None)
```

This came up in a real life project:

https://github.com/python-pillow/Pillow/blob/7bf5246b93cc89cfb9d6cca78c4719a943b10585/Tests/test_file_jpeg.py#L125

**Comment by htgoebel** [comment]
I assume this could be fixed by checking [here](https://github.com/pytest-dev/unittest2pytest/blob/develop/unittest2pytest/fixes/fix_self_assert.py#L433) whether 
a) `_method_map[method]` is a `CompOp` or `UnaryOp`
b) the right-hand-side (`required_args[1]`, AFAIR) is an expression.
If so, wrap the expression into parentheses.

We'd appreciate if you'd provide a pull-request with test-cases. Thanks.
